<?php /* Smarty version Smarty-3.1.3, created on 2014-03-20 08:48:27
         compiled from "/home/video/channel/template/browse_template/widget/common/module_static/module_static.tpl" */ ?>
<?php /*%%SmartyHeaderCode:422390186532a3adbc2e5f7-68103364%%*/if(!defined('SMARTY_DIR')) exit('no direct access allowed');
$_valid = $_smarty_tpl->decodeProperties(array (
  'file_dependency' => 
  array (
    '79739ce935fdef97ca0cada717a25eed7d4a8446' => 
    array (
      0 => '/home/video/channel/template/browse_template/widget/common/module_static/module_static.tpl',
      1 => 1387615250,
      2 => 'file',
    ),
  ),
  'nocache_hash' => '422390186532a3adbc2e5f7-68103364',
  'function' => 
  array (
  ),
  'has_nocache_code' => false,
  'version' => 'Smarty-3.1.3',
  'unifunc' => 'content_532a3adbc9d7f',
),false); /*/%%SmartyHeaderCode%%*/?>
<?php if ($_valid && !is_callable('content_532a3adbc9d7f')) {function content_532a3adbc9d7f($_smarty_tpl) {?><?php if (!is_callable('smarty_block_fis_widget')) include '/home/video/northwood/kanhuiqiu_com/kanhuiqiu/lib/smarty/libs/plugins/block.fis_widget.php';
?><?php $_smarty_tpl->smarty->_tag_stack[] = array('fis_widget', array()); $_block_repeat=true; echo smarty_block_fis_widget(array(), null, $_smarty_tpl, $_block_repeat);while ($_block_repeat) { ob_start();?>

<script type="text/javascript">
F._fileMap({'/browse_static/widget/common/module_static/module_static_78c4e92b.js' : ['/browse_static/common/lib/tangram/plugin/draggable/draggable.js',
'/browse_static/common/lib/tangram/plugin/sortable/sortable.js',
'/browse_static/common/lib/tangram/plugin/fx/fx.js',
'/browse_static/common/lib/tangram/plugin/selectable/selectable.js',
'/browse_static/common/lib/tangram/core/core.js',
'/browse_static/common/ui/vs/loadimg/loadimg.js',
'/browse_static/common/ui/vs/tmpl/tmpl.js',
'/browse_static/common/ui/vs/client/client.js',
'/browse_static/common/ui/vs/DetailTip/DetailTip.js',
'/browse_static/common/ui/vs/lazyload/lazyload.js',
'/browse_static/common/ui/vs/ABTest/ABTest.js',
'/browse_static/common/ui/vs/vipConfig/vipConfig.js',
'/browse_static/common/ui/vs/showFeedBack/showFeedBack.js',
'/browse_static/common/ui/vs/vipRegisterPopup/vipRegisterPopup.js',
'/browse_static/common/ui/vs/subDetailTip/subDetailTip.js',
'/browse_static/common/ui/vs/statistics/statistics.js',
'/browse_static/common/ui/vs/bdPassPop/bdPassPop.js',
'/browse_static/common/ui/vs/scrolling/scrolling.js',
'/browse_static/common/ui/vs/SiteList/SiteList.js',
'/browse_static/common/ui/vs/utility/mask/mask.js',
'/browse_static/common/ui/vs/utility/dialog/dialog.js',
'/browse_static/common/ui/vs/loginCheck/loginCheck.js',
'/browse_static/common/ui/vs/vipPlayPortal/vipPlayPortal.js',
'/browse_static/common/ui/vs/vipInfo/vipInfo.js',
'/browse_static/common/ui/vs/vs.js',
'/browse_static/common/ui/baidutemplate/baidutemplate.js',
'/browse_static/common/ui/magic/Slider/Slider.js',
'/browse_static/common/ui/magic/Popup/Popup.js',
'/browse_static/common/ui/magic/_query/_query.js',
'/browse_static/common/ui/magic/Tab/Tab.js',
'/browse_static/common/ui/magic/Base/Base.js',
'/browse_static/common/ui/magic/Tooltip/Tooltip.js',
'/browse_static/common/ui/magic/Mask/Mask.js',
'/browse_static/common/ui/magic/Carousel/$button/$button.js',
'/browse_static/common/ui/magic/Carousel/Carousel.js',
'/browse_static/common/ui/magic/Pager/Pager.js',
'/browse_static/common/ui/magic/Background/$styleBox/$styleBox.js',
'/browse_static/common/ui/magic/Background/Background.js',
'/browse_static/common/ui/magic/Dialog/Dialog.js',
'/browse_static/common/ui/magic/control/Tooltip/Tooltip.js',
'/browse_static/common/ui/magic/control/Layer/Layer.js',
'/browse_static/common/ui/magic/control/Carousel/$itemModify/$itemModify.js',
'/browse_static/common/ui/magic/control/Carousel/$autoScroll/$autoScroll.js',
'/browse_static/common/ui/magic/control/Carousel/$button/$button.js',
'/browse_static/common/ui/magic/control/Carousel/$fx/$fx.js',
'/browse_static/common/ui/magic/control/Carousel/Carousel.js',
'/browse_static/common/ui/magic/control/Dialog/$mask/$mask.js',
'/browse_static/common/ui/magic/control/Dialog/Dialog.js',
'/browse_static/common/ui/magic/control/Slider/$fx/$fx.js',
'/browse_static/common/ui/magic/control/Slider/$cache/$cache.js',
'/browse_static/common/ui/magic/control/Slider/Slider.js',
'/browse_static/common/ui/magic/control/Popup/Popup.js',
'/browse_static/common/ui/magic/control/Tab/Tab.js',
'/browse_static/common/ui/magic/control/Suggestion/Suggestion.js',
'/browse_static/common/ui/magic/control/control.js',
'/browse_static/common/ui/magic/setup/slider/slider.js',
'/browse_static/common/ui/magic/setup/tab/tab.js',
'/browse_static/common/ui/magic/setup/suggestion/suggestion.js',
'/browse_static/common/ui/magic/setup/carousel/carousel.js',
'/browse_static/common/ui/magic/setup/pager/pager.js',
'/browse_static/common/ui/magic/setup/background/background.js',
'/browse_static/common/ui/magic/setup/dialog/dialog.js',
'/browse_static/common/ui/magic/setup/setup.js',
'/browse_static/common/ui/magic/magic.js',
'/browse_static/common/ui/eventcenter/eventcenter.js',
'/browse_static/widget/common/header_baoku_player/header_baoku_player.js',
'/browse_static/widget/common/tabtoplist/tabtoplist.js',
'/browse_static/widget/common/gamepromo/gamepromo.js',
'/browse_static/widget/common/userbar/userbar.js',
'/browse_static/widget/common/navbar/navbar.js',
'/browse_static/widget/common/searchKeyword/searchKeyword.js',
'/browse_static/widget/common/new_search/new_search.js',
'/browse_static/widget/common/searchbox/searchbox.js',
'/browse_static/widget/common/backtop/backtop.js',
'/browse_static/widget/common/feedback/feedback.js',
'/browse_static/widget/common/tabpicarea/tabpicarea.js',
'/browse_static/widget/common/header_hao123/header_hao123.js',
'/browse_static/widget/common/header_baoku/header_baoku.js',
'/browse_static/widget/common/ui_searchbox/ui_searchbox.js',
'/browse_static/widget/common/focuslayer/focuslayer.js',
'/browse_static/widget/common/focuscarousel/focuscarousel.js']});
</script>
<link type="text/css" rel="stylesheet" href="/browse_static/widget/common/module_static/module_static_ae68856a.css"/>
<?php $_block_content = ob_get_clean(); $_block_repeat=false; echo smarty_block_fis_widget(array(), $_block_content, $_smarty_tpl, $_block_repeat);  } array_pop($_smarty_tpl->smarty->_tag_stack);?>
<?php }} ?>